name: Continuous Integration

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.3", "head"]
        operating-system: [ubuntu-latest]
        include:
          - ruby: "3.0"
            operating-system: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake
